// Default placeholder images from Unsplash
export const PLACEHOLDER_IMAGES = {
  hero: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1920&q=80",
  heroAlt: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&q=80",
  about: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
  contact: "https://images.unsplash.com/photo-1560520653-9e0e4c89eb11?w=1200&q=80",
  plotLandscape1: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
  plotLandscape2: "https://images.unsplash.com/photo-1625244724120-1fd1d34d00f6?w=800&q=80",
  plotLandscape3: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
  plotAerial1: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
  plotAerial2: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
  plotAerial3: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80",
  gallery1: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80",
  gallery2: "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&q=80",
  gallery3: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80",
  gallery4: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
  gallery5: "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&q=80",
  gallery6: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800&q=80",
};

export const SEED_PROJECTS = [
  {
    title: "RK Green Valley",
    slug: "rk-green-valley",
    location: "Shadnagar, Hyderabad",
    description:
      "RK Green Valley is a premium 50-acre gated community venture offering DTCP approved open plots in the rapidly developing Shadnagar corridor. With lush green landscapes, 40ft wide internal roads, underground drainage, and 24/7 security, this venture sets a new benchmark for plot developments. Located just 15 minutes from the proposed Regional Ring Road, this is the ideal investment for those seeking both tranquility and connectivity.",
    shortDescription:
      "Premium 50-acre gated community with DTCP approved plots near Shadnagar. Wide roads, full amenities, and excellent connectivity.",
    price: "₹15,999/sq.yd",
    priceRange: "₹15,999 - ₹22,999 per sq.yd",
    plotSizes: "150 - 500 sq.yds",
    totalArea: "50 Acres",
    totalPlots: 320,
    status: "ongoing" as const,
    featured: true,
    thumbnail: PLACEHOLDER_IMAGES.plotLandscape1,
    heroImage: PLACEHOLDER_IMAGES.plotAerial1,
    galleryImages: [
      PLACEHOLDER_IMAGES.gallery1,
      PLACEHOLDER_IMAGES.gallery2,
      PLACEHOLDER_IMAGES.gallery3,
      PLACEHOLDER_IMAGES.gallery4,
    ],
    layoutImage: PLACEHOLDER_IMAGES.plotAerial1,
    amenities: [
      "40ft & 30ft Wide Roads",
      "Underground Drainage",
      "Electricity with Street Lights",
      "Overhead Water Tank",
      "Children's Play Area",
      "Landscaped Gardens",
      "24/7 Security with CCTV",
      "Compound Wall",
      "Avenue Plantation",
      "Community Hall",
    ],
    highlights: [
      "DTCP Approved Layout",
      "RERA Registered",
      "15 min from Regional Ring Road",
      "Close to NH-44",
      "Near Educational Institutions",
      "Banks & ATMs Nearby",
    ],
    coordinates: { lat: 17.0671, lng: 78.2025 },
  },
  {
    title: "RK Paradise Enclave",
    slug: "rk-paradise-enclave",
    location: "Maheshwaram, Hyderabad",
    description:
      "RK Paradise Enclave is a beautifully planned 35-acre residential plot venture located in the thriving Maheshwaram corridor. This RERA registered venture features excellent infrastructure including blacktop roads, storm water drains, and decorative entrance archways. With proximity to the Outer Ring Road and major IT hubs, Paradise Enclave offers the perfect blend of suburban peace and urban accessibility.",
    shortDescription:
      "35-acre RERA registered venture in Maheshwaram with premium infrastructure and proximity to ORR & IT corridor.",
    price: "₹18,500/sq.yd",
    priceRange: "₹18,500 - ₹25,000 per sq.yd",
    plotSizes: "167 - 333 sq.yds",
    totalArea: "35 Acres",
    totalPlots: 210,
    status: "ongoing" as const,
    featured: true,
    thumbnail: PLACEHOLDER_IMAGES.plotLandscape2,
    heroImage: PLACEHOLDER_IMAGES.plotAerial2,
    galleryImages: [
      PLACEHOLDER_IMAGES.gallery3,
      PLACEHOLDER_IMAGES.gallery4,
      PLACEHOLDER_IMAGES.gallery5,
      PLACEHOLDER_IMAGES.gallery6,
    ],
    layoutImage: PLACEHOLDER_IMAGES.plotAerial2,
    amenities: [
      "40ft & 33ft BT Roads",
      "Storm Water Drains",
      "Electricity & Street Lighting",
      "Bore Well & Water Supply",
      "Jogging Track",
      "Meditation Garden",
      "Entrance Archway",
      "Security Cabin",
      "Avenue Plantation",
      "Open Gym Area",
    ],
    highlights: [
      "RERA Registered",
      "10 min from ORR",
      "Near Rajiv Gandhi International Airport",
      "Close to TSPA Academy",
      "Hospitals Within 5 km",
      "Schools & Colleges Nearby",
    ],
    coordinates: { lat: 17.1247, lng: 78.4378 },
  },
  {
    title: "RK Sunrise City",
    slug: "rk-sunrise-city",
    location: "Adibatla, Hyderabad",
    description:
      "RK Sunrise City is an upcoming world-class 75-acre township project near Adibatla, one of the fastest-growing destinations in Hyderabad. This mega venture will feature premium residential plots with access to club house facilities, swimming pool, tennis courts, and more. Located adjacent to the Pharma City SEZ and near major aerospace & defense corridors, this is the future of premium living.",
    shortDescription:
      "Upcoming 75-acre mega township near Adibatla with club house, sports facilities, and proximity to Pharma City SEZ.",
    price: "₹12,999/sq.yd",
    priceRange: "₹12,999 - ₹19,500 per sq.yd",
    plotSizes: "200 - 600 sq.yds",
    totalArea: "75 Acres",
    totalPlots: 480,
    status: "upcoming" as const,
    featured: true,
    thumbnail: PLACEHOLDER_IMAGES.plotLandscape3,
    heroImage: PLACEHOLDER_IMAGES.plotAerial3,
    galleryImages: [
      PLACEHOLDER_IMAGES.gallery1,
      PLACEHOLDER_IMAGES.gallery5,
      PLACEHOLDER_IMAGES.gallery2,
      PLACEHOLDER_IMAGES.gallery6,
    ],
    layoutImage: PLACEHOLDER_IMAGES.plotAerial3,
    amenities: [
      "60ft & 40ft Wide Roads",
      "Club House with Swimming Pool",
      "Tennis & Badminton Courts",
      "Cycling Track",
      "Amphitheatre",
      "Commercial Complex",
      "Temple & Community Space",
      "Rain Water Harvesting",
      "Solar Street Lighting",
      "Grand Entrance with Water Feature",
    ],
    highlights: [
      "DTCP & RERA Approved",
      "Adjacent to Pharma City SEZ",
      "Near Aerospace & Defense Hub",
      "Proposed Metro Connectivity",
      "5 min from ORR",
      "Premium Township Living",
    ],
    coordinates: { lat: 17.1742, lng: 78.5258 },
  },
  {
    title: "RK Heritage Heights",
    slug: "rk-heritage-heights",
    location: "Shamshabad, Hyderabad",
    description:
      "RK Heritage Heights is a completed and fully developed 25-acre residential venture near Shamshabad. All infrastructure is in place with families already residing in the community. This sold-out venture stands as a testament to RK Infracon's commitment to quality and customer satisfaction. Limited resale plots may be available.",
    shortDescription:
      "Completed 25-acre residential venture near Shamshabad. Fully developed with families in residence. A testament to quality.",
    price: "₹22,000/sq.yd",
    priceRange: "₹22,000 - ₹28,000 per sq.yd",
    plotSizes: "150 - 300 sq.yds",
    totalArea: "25 Acres",
    totalPlots: 180,
    status: "completed" as const,
    featured: false,
    thumbnail: PLACEHOLDER_IMAGES.plotAerial1,
    heroImage: PLACEHOLDER_IMAGES.plotLandscape1,
    galleryImages: [
      PLACEHOLDER_IMAGES.gallery2,
      PLACEHOLDER_IMAGES.gallery4,
      PLACEHOLDER_IMAGES.gallery6,
      PLACEHOLDER_IMAGES.gallery1,
    ],
    layoutImage: PLACEHOLDER_IMAGES.plotLandscape1,
    amenities: [
      "40ft BT Roads",
      "Underground Drainage",
      "24/7 Water Supply",
      "Electricity with Backup",
      "Park & Garden",
      "Security with CCTV",
      "Compound Wall",
      "Avenue Plantation",
    ],
    highlights: [
      "Fully Developed",
      "Families in Residence",
      "Near RGIA Airport",
      "Close to ORR",
      "Schools & Hospitals Nearby",
      "Excellent Appreciation",
    ],
    coordinates: { lat: 17.2403, lng: 78.4294 },
  },
];

export const AMENITY_ICONS: Record<string, string> = {
  "road": "🛣️",
  "drainage": "🚰",
  "electricity": "⚡",
  "water": "💧",
  "play": "🎮",
  "garden": "🌳",
  "security": "🛡️",
  "wall": "🧱",
  "plantation": "🌿",
  "community": "🏛️",
  "club": "🏊",
  "sports": "🎾",
  "cycling": "🚴",
  "temple": "🛕",
  "solar": "☀️",
  "rain": "🌧️",
  "commercial": "🏪",
  "gym": "💪",
  "jogging": "🏃",
  "meditation": "🧘",
  "amphitheatre": "🎭",
  "entrance": "🚪",
  "bore": "🔧",
  "default": "✅",
};

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "Projects", href: "/projects" },
  { label: "Gallery", href: "/gallery" },
  { label: "About Us", href: "/about" },
  { label: "Contact", href: "/contact" },
];

export const COMPANY_INFO = {
  name: "RK Infracon",
  tagline: "Trust In Us",
  phone: "8499900100",
  email: "info@rkinfracon.in",
  address: "Uppal, Hyderabad, Telangana, India",
  workingHours: "Mon - Sat: 9:30 AM to 8:30 PM",
  founded: "2018",
  experience: "15+",
  happyCustomers: "2000+",
  projectsDelivered: "15+",
  socialLinks: {
    facebook: "https://facebook.com/rkinfracon",
    instagram: "https://instagram.com/rkinfracon",
    youtube: "https://youtube.com/@rkinfracon",
    linkedin: "https://linkedin.com/company/rkinfracon",
  },
};
